config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tambos do
    resources :cows, except: %i[index delete] do
      resources :events, except: %i[index]
    end
    get 'search_cow', to: 'cows#search_cow'
    get 'cows_to_excel', to: 'cows#cows_to_excel'
  end

  resources :notifications
  post 'notifications/:id/mark_unread', to: 'notifications#mark_unread',
                                        as: :mark_unread
  post 'notifications/:id/mark_read', to: 'notifications#mark_read',
                                      as: :mark_read
  get 'notifications_read', to: 'notifications#notifications_read',
                            as: :notifications_read

  devise_for :users, skip: %i[registration]
  resources :users, only: %i[show update edit]
  get '/user/calendar', to: 'users#calendar'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'home#index'
end

app/models/tambo.rb
class Tambo < ApplicationRecord
  belongs_to :user
  has_one_attached :logo
  has_many :cows, :dependent => :destroy
  has_many :notifications, :dependent => :destroy

  validates :name, presence: true

  default_scope { order(name: :asc) }

  def to_s
    name
  end

  def display_logo
    if logo.attached?
      logo
    else
      'tambo_defaut.png'
    end
  end
end

app/controllers/tambos_controller.rb
# frozen_string_literal: true

# describe tambo controller
class TambosController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :set_tambo, only: %i[show edit update destroy]

  def index
    @tambos = current_user.tambos
  end

  def create
    @tambo = Tambo.new(tambo_params.merge(user_id: current_user.id))
    respond_to do |format|
      if @tambo.save
        format.html { redirect_to @tambo, notice: 'Tambo creado con éxito.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @tambo.update(tambo_params)
        format.html { redirect_to @tambo, notice: 'El tambo se ha actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @tambo }
      else
        format.html { render :edit }
        format.json { render json: @tambo.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @vacas = @tambo.cows.vacas
    @vaquillonas = @tambo.cows.vaquillonas
    @cow = Cow.new
  end

  private

  def set_tambo
    @tambo = current_user.tambos.find(params[:id])
  end

  def tambo_params
    params.require(:tambo).permit(:name,
                                  :address,
                                  :phone_contact,
                                  :map_position,
                                  :user_id,
                                  :logo,
                                  :notification_color)
  end
end

app/views/tambos/_form.html.erb
<%= form_with(model: tambo, local: true, class: "form-horizontal") do |form| %>
  <div class="card-body card-block">
    <div class="row form-group">
      <%= image_tag(tambo.display_logo, class: "tambo-logo") %>
    </div>
    <div class="row form-group">
      <div class="col col-md-3">
        <%= form.label :logo, class: "form-control-label" %>
      </div>
      <div class="col-12 col-md-9">
        <div class="input-group">
          <div class="custom-file">
            <%= form.file_field :logo, class: "custom-file-input" %>
            <label class="custom-file-label" >Seleccione..</label>
          </div>
        </div>
      </div>
    </div>
    <div class="row form-group">
      <div class="col col-md-3">
        <%= form.label :name, class: "form-control-label" %>
      </div>
      <div class="col-12 col-md-9">
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="row form-group">
      <div class="col col-md-3">
        <%= form.label :notification_color, class: "form-control-label" %>
      </div>
      <div class="col-12 col-md-9">
        <%= form.text_field :notification_color, class: "form-control" %>
      </div>
    </div>
    <div class="row form-group">
      <div class="col col-md-3">
        <%= form.label :address, class: "form-control-label" %>
      </div>
      <div class="col-12 col-md-9">
        <%= form.text_field :address, class: "form-control" %>
      </div>
    </div>
    <div class="row form-group">
      <div class="col col-md-3">
        <%= form.label :phone_contact, class: "form-control-label" %>
      </div>
      <div class="col-12 col-md-9">
        <%= form.text_field :phone_contact, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= form.submit "Guardar", class: "btn btn-info btn-sm" %>
  </div>
<% end %>

app/views/tambos/_table_cow.html.erb
<table id="bootstrap-data-table-2" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Caravana</th>
      <th>F. Parto</th>
      <th>Nº Servicio</th>
      <th>F. Servicio</th>
      <th>Fecha</th>
      <th>Toro</th>
    </tr>
  </thead>
  <tbody>
    <% @vacas.no_dry.each do |cow| %>
      <tr>
        <td class= "stat-<%= cow.status %>"><%= cow.caravan_with_type %></td>
        <td><%= cow.due_date %></td>
        <td><%= cow.service_num %></td>
        <td><%= cow.service_date %></td>
        <td><%= cow.date %></td>
        <td><%= cow.bull %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tambos/edit.html.erb
<div class="card border border-secondary">
  <div class="card-header">
    <strong>Editar Establecimiento</strong>
  </div>
  <%= render 'form', tambo: @tambo %>
</div>
  

app/views/tambos/index.html.erb
<div class="row">
  <% @tambos.each do |tambo| %>
    <%= tambo_hover_color(tambo).html_safe %>
    <div class="col-md-4">
      <%= link_to tambo_path(tambo) do %>
        <aside id="tambo_id_<%= tambo.id %>" class="profile-nav alt">
          <section class="card">
            <div class="card-header user-header alt bg-dark">
              <div class="media">
                <%= image_tag tambo.display_logo, class: "align-self-center rounded-circle mr-3", style: "width:65px; height:65px;" %>
                <div class="media-body">
                  <h2 class="text-light display-6"><%= tambo.name %></h2>
                  <p><%= tambo.address %></p>
                </div>
              </div>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <i class="fa fa-dot-circle-o"></i> 
                Vacas secas 
                <span class="badge badge-dry pull-right">
                  <%= tambo.cows.dry.count %>
                </span>
              </li>
              <li class="list-group-item">
                <i class="fa fa-dot-circle-o"></i> 
                Vacas preñadas 
                <span class="badge badge-pregnant pull-right">
                  <%= tambo.cows.pregnant.count %>
                </span>
              </li>
              <li class="list-group-item">
                <i class="fa fa-dot-circle-o"></i> 
                Vacas vacía
                <span class="badge badge-empty pull-right">
                  <%= tambo.cows.empty.count %>
                </span>
              </li>
              <li class="list-group-item">
                <i class="fa fa-dot-circle-o"></i> 
                Vacas para descarte 
                <span class="badge badge-discard pull-right r-activity">
                  <%= tambo.cows.discard.count %>
                </span>
              </li>
            </ul>
          </section>
        </aside>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tambos/new.html.erb
<div class="card border border-secondary">
  <div class="card-header">
    <strong>Nuevo Establecimiento</strong>
  </div>
  <%= render 'form', tambo: @tambo %>
</div>

app/views/tambos/show.html.erb
<div class="card border border-secondary">
  <div class="card-header" style="border-bottom:none">
    <%= image_tag(@tambo.display_logo, class: "tambo-logo-mini") %>
    <strong>
      <%= @tambo.name %>
    </strong>
    | <%= @tambo.address %> - Tel: <%= @tambo.phone_contact %>
    <small>
      <span class="float-right mt-1">
        <%= link_to 'Editar', edit_tambo_path(@tambo), class: 'edit-btn-cust btn-info' %>
      </span>
    </small>
  </div>
</div>

<div class="card border border-secondary">
  <div class="card-header">
    <strong>
      Buscar
    </strong>
  </div>
  <div class="card-body">
    <%= form_tag(tambo_search_cow_path(@tambo), method: :get) do %>
    <div class="input-group">
      <%= text_field_tag(:caravan, params[:caravan], placeholder: "ingrese numero de caravana", class: "form-control") %>
      <div class="input-group-btn">
        <%= submit_tag "Buscar", class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </div>
</div>
  
<div id="accordion">
  <div class="card border border-secondary">
    <div id="headingTwo" class="card-header hand-mouse" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
      <strong>
        Vacas en el Tambo: <%= @vacas.no_dry.count %>
      </strong>
      <span class="float-right">
        <%= image_tag "2_cow_icon.png", class: "cow-reference" %> Preñada - 
        <%= image_tag "3_cow_icon.png", class: "cow-reference" %> Descarte - 
        <%= image_tag "4_cow_icon.png", class: "cow-reference" %> Vacía - 
        <%= image_tag "6_cow_icon.png", class: "cow-reference" %> Servida
      </span>
    </div>
    <div id="collapseTwo" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body card-block">
        <%= link_to new_tambo_cow_path(@tambo) do %>
          <div class="cow-item">
            <i class="fa fa-plus-square cow-add-icon"></i></br>
            Agregar
          </div>
        <% end %>
        <% @vacas.no_dry.each do |cow| %>
          <%= link_to tambo_cow_path(@tambo, cow) do %>
            <div class="cow-item">
              <%= image_tag "#{cow.status_number}_cow_icon.png" %></br>
              <%= cow.caravan_with_type %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card border border-secondary">
    <div id="headingThree" class="card-header hand-mouse" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
      <strong>
        Vacas secas: <%= @vacas.dry.count %>
      </strong>
      <span class="float-right">
        <%= image_tag "1_cow_icon.png", class: "cow-reference" %> Seca
      </span>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
      <div class="card-body card-block"> 
        <% @vacas.dry.each do |cow| %>
          <%= link_to tambo_cow_path(@tambo, cow) do %>
            <div class="cow-item">
              <%= image_tag "#{cow.status_number}_cow_icon.png" %></br>
              <%= cow.caravan_with_type %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card border border-secondary">
    <div id="headingFor" class="card-header hand-mouse" data-toggle="collapse" data-target="#collapseFor" aria-expanded="false" aria-controls="collapseFor">
      <strong>
        Plantel de vaquillonas: <%= @vaquillonas.count %>
      </strong>
    </div>
    <div id="collapseFor" class="collapse" aria-labelledby="headingFor" data-parent="#accordion">
      <div class="card-body card-block"> 
        <%= link_to new_tambo_cow_path(@tambo) do %>
          <div class="cow-item">
              <i class="fa fa-plus-square cow-add-icon"></i></br>
              Agregar
          </div>
        <% end %>
        <% @vaquillonas.each do |cow| %>
          <%= link_to tambo_cow_path(@tambo,  cow) do %>
            <div class="cow-item">
                <%= image_tag "#{cow.status_number}_cow_icon.png" %></br>
              <%= cow.caravan_with_type %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card border border-secondary">
    <div id="headingFive" class="card-header hand-mouse" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
      <strong class="card-title">Tabla</strong>
      <span class="float-right">
        <%= link_to 'Imprimir', tambo_cows_to_excel_path(@tambo, format: :xlsx), class: 'edit-btn-cust btn-info'  %>
      </span>
    </div>
    <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordion">
      <div class="card-body">
          <%= render partial: "table_cow" %>
      </div>
    </div>
  </div>

</div>