config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tambos do
    resources :cows, except: %i[index delete] do
      resources :events, except: %i[index]
    end
    get 'search_cow', to: 'cows#search_cow'
    get 'cows_to_excel', to: 'cows#cows_to_excel'
  end

  resources :notifications
  post 'notifications/:id/mark_unread', to: 'notifications#mark_unread',
                                        as: :mark_unread
  post 'notifications/:id/mark_read', to: 'notifications#mark_read',
                                      as: :mark_read
  get 'notifications_read', to: 'notifications#notifications_read',
                            as: :notifications_read

  devise_for :users, skip: %i[registration]
  resources :users, only: %i[show update edit]
  get '/user/calendar', to: 'users#calendar'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'home#index'
end

app/models/notification.rb
# frozen_string_literal: true

# Notification class
class Notification < ApplicationRecord
  belongs_to :tambo
  belongs_to :cow
  belongs_to :event
  belongs_to :user

  scope :unread, -> { where(read: false).order(notify_date: :desc) }
  scope :read, -> { where(read: true).order(notify_date: :desc) }
  default_scope { order(notify_date: :desc, read: :asc) }

  after_create :set_title_and_description

  private

  def set_title_and_description
    self.description = event.notify_description
    self.title = "#{tambo.name} - #{cow.caravan_with_type} - #{description}"
    save
  end
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

# notifications controller
class NotificationsController < ApplicationController
  def index
    @all_notifications_unread = current_user.notifications.unread
    @notifications_unread = current_user.today_notification
                                        .paginate(page: params[:page],
                                                  per_page: 5)
  end

  def notifications_read
    @notifications_read = current_user.notifications.read
                                      .paginate(page: params[:page],
                                                per_page: 10)
  end

  def show
    @notification = current_user.notifications.find(params[:id])
    @notification.update(read: true)
  end

  def mark_unread
    @notification = current_user.notifications.find(params[:id])
    respond_to do |format|
      if @notification.update(read: false)
        format.html { redirect_to notifications_path, notice: 'La notificación se ha actualizado correctamente.' }
      else
        format.html { render :index }
      end
    end
  end

  def mark_read
    @notification = current_user.notifications.find(params[:id])
    respond_to do |format|
      if @notification.update(read: true)
        format.html { redirect_to notifications_path, notice: 'La notificación se ha actualizado correctamente.' }
      else
        format.html { render :index }
      end
    end
  end
end

app/views/notifications/index.html.erb
<div class="card">
  <div class="card-header">
    <strong>Notificaciones</strong>
  </div>
  <div class="card-body card-block">
    <% if @notifications_unread.blank? %>
      <p>No existen notificaciones sin leer hoy.</p>
    <% else %>
      <p>Notificaciones sin leer</p>
      <% @notifications_unread.each do |notification| %>
        <%= link_to notification_path(notification) do %>
          <div class="toast toast--blue add-margin">
            <div class="toast__icon"><i class="fa fa-envelope"></i></div>
            <div class="toast__content">
              <p class="toast__type"><%= notification.tambo %></p>
              <p class="toast__message">
                <strong><%= notification.notify_date %> - </strong> 
                <strong>Caravana: <%= notification.cow.caravan_with_type %> - <%= notification.description %></strong>
              </p>
            </div>
            <%= link_to mark_read_path(notification),  method: :post do %>
              <div class="toast__close"><i class="fa fa-times"></i></div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
    </br>
    <div class="apple_pagination">
      <%= will_paginate @notifications_unread, :container => false %>
    </div>
    <%= link_to 'Ver leídas', notifications_read_path() %>
  </div>
</div>

app/views/notifications/notifications_read.html.erb
<div class="card">
  <div class="card-header">
    <strong>Notificaciones leídas</strong>
  </div>
  <div class="card-body card-block">
    <% @notifications_read.each do |notification| %>
      <%= link_to notification_path(notification) do %>
        <div class="toast toast--grey add-margin">
          <div class="toast__icon"><i class="fa fa-envelope-o"> </i></div>
          <div class="toast__content">
            <p class="toast__type__read"><%= notification.tambo %></p>
            <p class="toast__message">
              <%= notification.notify_date %> -
              Caravana: <%= notification.cow.caravan_with_type %> - <%= notification.description %>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
    <div class="apple_pagination">
      <%= will_paginate @notifications_read, :container => false %>
    </div>
  </div>
</div>

app/views/notifications/show.html.erb
<div class="card border border-status">
  <div class="card-header">
    <strong>Notificación</strong>
  </div>
  <div class="card-body card-block">
    
    <div class="row form-group">
      <div class="col col-md-3">
        <label class="form-control-label">Fecha:</label>
      </div>
      <div class="col-12 col-md-9">
        <input class="form-control" readonly="readonly" type="text" value=<%= @notification.notify_date %>>
      </div>
    </div>

    <div class="row form-group">
      <div class="col col-md-3">
        <label class="form-control-label">Tambo:</label>
      </div>
      <div class="col-12 col-md-9">
        <input class="form-control" readonly="readonly" type="text" value="<%= @notification.tambo.name %>">
      </div>
    </div>

    <div class="row form-group">
      <div class="col col-md-3">
        <label class="form-control-label">Vaca:</label>
      </div>
      <div class="col-12 col-md-9">
        <input class="form-control" readonly="readonly" type="text" value=<%= @notification.cow.caravan %>>
      </div>
    </div>

    <div class="row form-group">
      <div class="col col-md-3">
        <label class="form-control-label">Evento:</label>
      </div>
      <div class="col-12 col-md-9">
        <input class="form-control" readonly="readonly" type="text" value="<%= @notification.event.date_event %> - <%= @notification.event.action_name %>">
      </div>
    </div>

    <div class="row form-group">
      <div class="col col-md-3">
        <label class="form-control-label">Descripción:</label>
      </div>
      <div class="col-12 col-md-9">
        <input class="form-control" readonly="readonly" type="text" value="<%= @notification.description %>">
      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to  "Atras", notifications_path(), class: 'btn btn-primary btn-sm' %>
    <%= link_to  "Marcar no leído", mark_unread_path(@notification),  method: :post, class: 'btn btn-success btn-sm' %>
  </div>
</div>