config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tambos do
    resources :cows, except: %i[index delete] do
      resources :events, except: %i[index]
    end
    get 'search_cow', to: 'cows#search_cow'
    get 'cows_to_excel', to: 'cows#cows_to_excel'
  end

  resources :notifications
  post 'notifications/:id/mark_unread', to: 'notifications#mark_unread',
                                        as: :mark_unread
  post 'notifications/:id/mark_read', to: 'notifications#mark_read',
                                      as: :mark_read
  get 'notifications_read', to: 'notifications#notifications_read',
                            as: :notifications_read

  devise_for :users, skip: %i[registration]
  resources :users, only: %i[show update edit]
  get '/user/calendar', to: 'users#calendar'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'home#index'
end

app/models/cow.rb
# frozen_string_literal: true

# Cow class
class Cow < ApplicationRecord
  enum status: { dry: 1,      # Green  #0FA20B
                 pregnant: 2, # Blue   #221D8F
                 discard: 3,  # Red    #ED2F15
                 empty: 4,    # Yellow #EDE515
                 dead: 5,     # Black  #010101
                 served: 6 }  # Pink   #BD12B3

  enum cow_type: { cow: 1,
                   small_cow: 2,
                   small_cow_tambo: 3 }

  belongs_to :tambo, :dependent => :destroy 
  has_many :events, :dependent => :destroy

  validates :cow_type, presence: true
  validates :caravan, presence: true, numericality: { only_integer: true }
  validates :tambo_id, presence: true
  validates :status, presence: true
  validates_uniqueness_of :caravan, scope: :tambo_id

  default_scope do
    where.not(status: :dead)
         .order('caravan::integer ASC')
  end
  scope :no_dry, -> { where.not(status: :dry) }
  scope :vacas, -> { where(cow_type: [1, 3]) }
  scope :vaquillonas, -> { where(cow_type: 2) }

  def self.status_attributes_for_select
    statuses.map do |status, _|
      [I18n.t("activerecord.attributes.cow.statuses.#{status}"),
       status]
    end
  end

  def self.cow_type_attributes_for_select
    cow_types.map do |cow_type, _|
      [I18n.t("activerecord.attributes.cow.cow_types.#{cow_type}"),
       cow_type]
    end
  end

  def status_number
    read_attribute_before_type_cast(:status)
  end

  def status_name
    I18n.t("activerecord.attributes.cow.statuses.#{status}")
  end

  def cow_type_number
    read_attribute_before_type_cast(:cow_type)
  end

  def cow_type_name
    I18n.t("activerecord.attributes.cow.cow_types.#{cow_type}")
  end

  def caravan_with_type
    if cow_type_number == 3
      "#{caravan}VQ"
    else
      caravan
    end
  end

  def last_due_date
    events.gave_birth.try(:last).try(:date_event)
  end

  def count_served_after_gave_birth
    events.served.where('date_event >= ?', last_due_date).count
  end

  def last_service_date
    events.served.where('date_event >= ?', last_due_date).last.try(:date_event)
  end

  # Temporal method
  def self.create_served_event
    pregnant.each do |cow|
      next unless cow.events.served.blank?

      event_id = cow.events.pregnant.last.id
      pregnant_date = cow.events.pregnant.last.date_event
      Event.create(cow_id: cow.id, date_event: pregnant_date, action: 1)
      Event.create(cow_id: cow.id,
                   date_event: pregnant_date,
                   action: 2,
                   notify_date: pregnant_date + 190.days,
                   notify_description: 'Revisar para secar')
      Event.find(event_id).destroy
    end
  end
end

app/controllers/cows_controller.rb
# frozen_string_literal: true

# describe cows controller
class CowsController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :set_cow_and_tambos, only: %i[show edit update destroy]
  skip_before_action :verify_authenticity_token

  def new
    @tambo = current_user.tambos.find(params[:tambo_id])
    @cow = Cow.new
    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def create
    @cow = Cow.new(cow_params)
    @tambo = current_user.tambos.find(params[:tambo_id])
    @cow.tambo = @tambo
    respond_to do |format|
      if @cow.save
        if @cow.dead?
          format.html { redirect_to tambo_path(@tambo), notice: 'Vaca creada con éxito.' }
        else
          format.html { redirect_to tambo_cow_path(@tambo, @cow), notice: 'Vaca creada con éxito.' }
          format.json { render json: { status: 'OK', message: 'Vaca creada con éxito.', cow_id: @cow.id, tambo_id: @tambo.id } }
        end
      else
        format.html { render :new }
        format.json { render json: { status: 'ERROR', errors: @cow.errors.messages } }
      end
    end
  end

  def show
    @event = Event.new(cow_id: @cow.id)
  end

  def update
    respond_to do |format|
      if @cow.update(cow_params)
        if @cow.dead?
          format.html { redirect_to tambo_path(@tambo), notice: 'La vaca se ha actualizado correctamente.' }
        else
          format.html { redirect_to tambo_cow_path(@tambo, @cow), notice: 'La vaca se ha actualizado correctamente.' }
          format.json { render json: { status: 'OK', message: 'Vaca actualizada con éxito.', cow_id: @cow.id, tambo_id: @tambo.id } }
        end
      else
        format.html { render :edit }
        format.json { render json: @cow.errors, status: :unprocessable_entity }
      end
    end
  end

  def search_cow
    @tambo = current_user.tambos.find(params[:tambo_id])
    @cow = @tambo.cows.find_by(caravan: params[:caravan])
    respond_to do |format|
      if @cow.nil?
        format.html { redirect_to tambo_path(@tambo.id), alert: 'No se encontro vaca' }
        format.json { render json: { errors: 'No se encontro vaca' } }
      else
        format.html { redirect_to tambo_cow_path(@tambo, @cow) }
        format.json { render json: { status: 'OK' } }
      end
    end
  end

  def cows_to_excel
    @tambo = current_user.tambos.find(params[:tambo_id])
    @cows = @tambo.cows.vacas.no_dry
    respond_to do |format|
      format.xlsx do
        file_name = "Planilla_#{@tambo.name}_#{Time.now.strftime('%d_%m_%Y')}.xlsx".gsub(" ", "_")
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=#{file_name}"
      end
      format.html { render :cows_to_exel }
    end
  end

  private

  def set_cow_and_tambos
    @tambos = current_user.tambos
    @tambo = @tambos.find(params[:tambo_id])
    @cow = @tambo.cows.find(params[:id])
  end

  def cow_params
    params.require(:cow).permit(
      :caravan,
      :birth_date,
      :tambo_id,
      :status,
      :cow_type
    )
  end
end

app/views/cows/_form.html.erb
<%= form_with(model: @cow, url: [@tambo, @cow], id: "cow_form", class: "form-horizontal") do |form| %>
  <div class="card-body card-block">
    <div class="row form-group">
      <div class="col col-md-3">
        <%= form.label :cow_type, class: "form-control-label" %>
      </div>
      <div class="col-12 col-md-9">
        <%= form.select :cow_type, options_for_select(Cow.cow_type_attributes_for_select, @cow.cow_type), :prompt => "Seleccione..", :class => "form-control" %>
      </div>
    </div>
    <div class="row form-group">
      <div class="col col-md-3">
        <%= form.label :status, class: "form-control-label" %>
      </div>
      <div class="col-12 col-md-9">
        <%= form.select :status, options_for_select(Cow.status_attributes_for_select, @cow.status), :prompt => "Seleccione..", :class => "form-control" %>
      </div>
    </div>
    <div class="row form-group">
      <div class="col col-md-3">
        <%= form.label :caravan, class: "form-control-label" %>
      </div>
      <div class="col-12 col-md-9">
        <%= form.text_field :caravan, class: "form-control" %>
      </div>
    </div>
    <div class="row form-group">
      <div class="col col-md-3">
        <%= form.label :birth_date, class: "form-control-label" %>
      </div>
      <div class="col-12 col-md-9 input-group date" data-provide="datepicker">
        <%= form.text_field :birth_date, class: "form-control" %>
        <div class="input-group-addon">
          <span class="fa fa-calendar"></span>
        </div>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= form.submit "Guardar", id: "save_cow", class: "btn btn-info btn-sm" %>
  </div>
<% end %>

app/views/cows/edit.html.erb
<div class="card border border-secondary">
  <div class="card-header">
    <strong>Editar Vaca</strong>
  </div>
  <%= form_with(model: @cow, url: [@tambo, @cow], id: "",  local: true, class: "form-horizontal") do |form| %>
    <div class="card-body card-block">
      <div class="row form-group">
        <div class="col col-md-3">
          <%= form.label :cow_type, class: "form-control-label" %>
        </div>
        <div class="col-12 col-md-9">
          <%= form.select :cow_type, options_for_select(Cow.cow_type_attributes_for_select, @cow.cow_type), :prompt => "Seleccione..", :class => "form-control" %>
        </div>
      </div>
      <div class="row form-group">
        <div class="col col-md-3">
          <%= form.label :status, class: "form-control-label" %>
        </div>
        <div class="col-12 col-md-9">
          <%= form.select :status, options_for_select(Cow.status_attributes_for_select, @cow.status), :prompt => "Seleccione..", :class => "form-control" %>
        </div>
      </div>
      <div class="row form-group">
        <div class="col col-md-3">
          <%= form.label :caravan, class: "form-control-label" %>
        </div>
        <div class="col-12 col-md-9">
          <%= form.text_field :caravan, class: "form-control" %>
        </div>
      </div>
      <div class="row form-group">
        <div class="col col-md-3">
          <%= form.label :birth_date, class: "form-control-label" %>
        </div>
        <div class="col-12 col-md-9 input-group date" data-provide="datepicker">
          <%= form.text_field :birth_date, class: "form-control" %>
          <div class="input-group-addon">
            <span class="fa fa-calendar"></span>
          </div>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <%= form.submit "Guardar", id:"", class: "btn btn-info btn-sm" %>
    </div>
  <% end %>
</div>
  

app/views/cows/new.html.erb
<div class="card border border-secondary">
  <div class="card-header">
    <strong>Nueva Vaca</strong>
  </div>
  <%= form_with(model: @cow, url: [@tambo, @cow], class: "form-horizontal", data: { remote: false }) do |form| %>
    <div class="card-body card-block">
      <div class="row form-group">
        <div class="col col-md-3">
          <%= form.label :cow_type, class: "form-control-label" %>
        </div>
        <div class="col-12 col-md-9">
          <%= form.select :cow_type, options_for_select(Cow.cow_type_attributes_for_select, @cow.cow_type), :prompt => "Seleccione..", :class => "form-control" %>
        </div>
      </div>
      <div class="row form-group">
        <div class="col col-md-3">
          <%= form.label :status, class: "form-control-label" %>
        </div>
        <div class="col-12 col-md-9">
          <%= form.select :status, options_for_select(Cow.status_attributes_for_select, @cow.status), :prompt => "Seleccione..", :class => "form-control" %>
        </div>
      </div>
      <div class="row form-group">
        <div class="col col-md-3">
          <%= form.label :caravan, class: "form-control-label" %>
        </div>
        <div class="col-12 col-md-9">
          <%= form.text_field :caravan, class: "form-control" %>
        </div>
      </div>
      <div class="row form-group">
        <div class="col col-md-3">
          <%= form.label :birth_date, class: "form-control-label" %>
        </div>
        <div class="col-12 col-md-9 input-group date" data-provide="datepicker">
          <%= form.text_field :birth_date, class: "form-control" %>
          <div class="input-group-addon">
            <span class="fa fa-calendar"></span>
          </div>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <%= form.submit "Guardar", class: "btn btn-info btn-sm" %>
    </div>
  <% end %>
</div>
  

app/views/cows/show.html.erb
<%= status_color(@cow.read_attribute_before_type_cast(:status)).html_safe %>
<div class="card border border-secondary">
  <div class="card-header" style="border-bottom:none">
    <%= image_tag(@cow.tambo.display_logo, class: "tambo-logo-mini") %>
    <strong>
      <%= link_to @cow.tambo.name, tambo_path(@cow.tambo), class: 'tambo-link' %>
    </strong>
    | <%= @cow.tambo.address %> - Tel: <%= @cow.tambo.phone_contact %>
  </div>
</div>

<div class="card border border-status">
  <div class="card-header status-color">
    <div class="float-left">
      <strong>
        <%= image_tag "#{@cow.status_number}_cow_icon.png", class: 'cow-icon' %>
      </strong>
      <span class="cow-show-title">
        -
      </span>
      <span class="cow-show-title">
        <%= @cow.caravan_with_type %>
      </span>
      <span class="cow-show-title">
        -
      </span>
      <span class="cow-show-title">
        <%= @cow.status_name %>
      </span>
    </div>
    <div class="float-right">
      <small>
        <span class="float-right mt-1">
          <%= link_to 'Editar', edit_tambo_cow_path(@tambo, @cow), class: 'edit-btn-cust btn-info' %>
        </span>
      </small>
    </div>
  </div>
  <div class="card-body p-0 card-block">
    <table class="table table-hover table-striped table-align-middle mb-0">
      <thead>
        <tr>
          <th>Caravana</th>
          <th>Fecha</th>
          <th>Evento</th>
          <th>Toro</th>
          <th>Notificacion</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @cow.events.each do |event| %>
          <tr>
            <td><%= @cow.caravan_with_type %></td>
            <td><%= event.date_event%></td>
            <td><%= event.action_name %></td>
            <td><%= event.bull %></td>
            <td><%= event.notify_date %></td>
            <td>
              <%= link_to tambo_cow_event_path(@tambo, @cow, event) do %>
                <i class="fa fa-folder-open"></i>
              <% end %>
              <%= link_to edit_tambo_cow_event_path(@tambo, @cow, event) do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to tambo_cow_event_path(@tambo, @cow, event), method: :delete, data: { confirm: 'Esta seguro eliminar el evento?' } do %>
                <i class="fa fa-times"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <%= link_to new_tambo_cow_event_path(@tambo, @cow, @event), class: 'edit-btn-cust btn-info' do %>
      <i class="fa fa-plus-square"></i>  
      Agregar
    <% end %>
  </div>
</div>