config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tambos do
    resources :cows, except: %i[index delete] do
      resources :events, except: %i[index]
    end
    get 'search_cow', to: 'cows#search_cow'
    get 'cows_to_excel', to: 'cows#cows_to_excel'
  end

  resources :notifications
  post 'notifications/:id/mark_unread', to: 'notifications#mark_unread',
                                        as: :mark_unread
  post 'notifications/:id/mark_read', to: 'notifications#mark_read',
                                      as: :mark_read
  get 'notifications_read', to: 'notifications#notifications_read',
                            as: :notifications_read

  devise_for :users, skip: %i[registration]
  resources :users, only: %i[show update edit]
  get '/user/calendar', to: 'users#calendar'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'home#index'
end

app/views/layouts/_left_panel.html.erb
<aside id="left-panel" class="left-panel">
  <nav class="navbar navbar-expand-sm navbar-default">
    <div id="main-menu" class="main-menu collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"></li>
        <li class="active menu-title">MENU</li><!-- /.menu-title -->
        <li class="menu-item-has-children dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-th"></i>Tambos</a>
          <ul class="sub-menu children dropdown-menu">
            <% current_user.tambos.each do |tambo| %>
              <li><i class="fa fa-circle"></i><%= link_to tambo.name, tambo_path(tambo)%></li>
            <% end %>
            <li><i class="fa fa-plus-square"></i><%= link_to 'Nuevo', new_tambo_path %></li>
          </ul>
        </li>
        <li class="menu-item-has-children dropdown <%= check_notifications %>" >
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-bell"></i>Notificaciones</a>
          <ul class="sub-menu children dropdown-menu">
            <li><i class="fa fa-search"></i><%= link_to 'Ver', notifications_path() %></li>
          </ul>
        </li>
        <li class="menu-item-has-children dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-calendar"></i>Calendario</a>
          <ul class="sub-menu children dropdown-menu">
            <li><i class="fa fa-search"></i><%= link_to 'Ver', user_calendar_path() %></li>
          </ul>
        </li>
        <li class="menu-item-has-children dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-user"></i>Usuario</a>
          <ul class="sub-menu children dropdown-menu">
            <li><i class="fa fa-user"></i><%= link_to 'Perfil', edit_user_path(current_user.id)%></li>
            <li><i class="fa fa-power-off"></i><%= link_to 'Salir', destroy_user_session_path, method: "delete"%></li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</aside>

app/views/layouts/_right_panel.html.erb
<div id="right-panel" class="right-panel">
  <!-- Header-->
  <header id="header" class="header">
    <div class="top-left">
      <div class="navbar-header">
        <a class="navbar-brand" href="/"><%= image_tag 'logo.png' %></a>
        <a class="navbar-brand hidden" href="/"><%= image_tag 'logo2.png', alt: 'logo' %></a>
        <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
      </div>
    </div>
    <div class="top-right">
      <div class="header-menu">
        <div class="user-area dropdown float-right">
          <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag(current_user.display_avatar, class: "user-avatar rounded-circle") %>
          </a>
          <div class="user-menu dropdown-menu">
            <%= link_to edit_user_path(current_user.id), class: "nav-link" do %>
              <i class="fa fa-user"></i>Perfil
            <% end %>
            <%= link_to destroy_user_session_path, method: "delete", class: "nav-link" do %>
              <i class="fa fa-power-off"></i>Salir
            <% end %>  
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- /#header -->
  <!-- Content -->
  <div class="content">
    <%= yield %>
  </div>
  <!-- /.content -->
  <div class="clearfix"></div>

  <footer class="site-footer">
    <div class="footer-inner bg-white">
      <div class="row">
        <div class="col-sm-6">
          Copyright &copy; 2019 Milkit Admin
        </div>
        <div class="col-sm-6 text-right">
          Designed by 
          <a href="https://www.linkedin.com/in/gfagalde" target="_blank" >
            <%= image_tag 'milogo.png', alt: "", height:"30px" %>
          </a>
        </div>
      </div>
    </div>
  </footer>
  <!-- /.site-footer -->
</div>
<!-- /#right-panel -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Milkit Admin</title>
    <%= favicon_link_tag 'favicon.ico' %>
    
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
  </head>
  
  <body>
    <%= flash_notifications -%>
    <%= render partial: "/layouts/left_panel" %>
    <%= render partial: "/layouts/right_panel" %>
  </body>
</html>